services:
  # Backend
  api:
    build: .
    container_name: edith_api
    command: ["python", "-u", "edith/api.py"]
    volumes:
      - .:/app
      - /app/.venv
    ports:
      - "8000:8000"
      - "8080:8080"
    env_file:
      - .env
    stdin_open: true
    tty: true

  # Frontend
  frontend:
    image: node:22-alpine3.18
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules # Isolated volume for container-specific dependencies
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - api

  next-frontend:
    build:
      context: ./next-frontend
      dockerfile: Dockerfile
      target: dev
    env_file: ./next-frontend/.env
    volumes:
      - ./next-frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    depends_on:
      - api
  
    
    