import type { Metadata } from "next";
import "../globals.css";
import Headers from "@/components/header";

export const metadata: Metadata = {
  title: "Welcome to Edith",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <Headers />
    {children}
    </>
  );
}
